version: '3'

services:
  # walmart.product.api:
  #   container_name: walmart_productapi
  #   image: jmanuelabanto/productapi:latest
  #   build:
  #     context: .
  #     dockerfile: src/ms-products-go/Dockerfile
  #   environment:
  #     - MONGODB_URI=mongodb+srv://root:A123a@develop.oh3sr.mongodb.net/test?retryWrites=true&w=majority
  #     - MONGODB_NAME=test
  #   ports:
  #     - 5500:5500

  walmart.web.app:
    container_name: walmart_webapp
    image: jmanuelabanto/webapp:latest
    build:
      context: .
      dockerfile: src/lider-app/Dockerfile
    command: serve -s build -l 80
    ports:
      - 3000:80